Repository Omega-Numworks/Omega, pull requests merged in 2019-12, with the labels that each got.

#99 External application, API v2
  apps/code/editor_controller.cpp
  apps/code/editor_controller.h
  apps/external/Makefile
  apps/external/archive.cpp
  apps/external/extapp_api.cpp
  apps/external/extapp_api.h
  ion/include/ion/storage.h
  kandinsky/include/kandinsky/color.h
  kandinsky/include/kandinsky/context.h
  kandinsky/include/kandinsky/ion_context.h
  python/port/genhdr/qstrdefs.in.h
  python/port/helpers.cpp
  python/port/mod/kandinsky/modkandinsky.cpp
  python/port/mod/kandinsky/modkandinsky.h
  python/port/mod/kandinsky/modkandinsky_table.c
  python/port/port.cpp
  python/port/port.h
Labels: Change, Work in progress

#103 Disable "External" in Dutch exam mode
  apps/home/controller.cpp
Labels: Feature

#107 Reworked exam mode, fixed #106
  apps/apps_container.cpp
  apps/calculation/calculation_store.cpp
  apps/exam_pop_up_controller.cpp
  apps/global_preferences.cpp
  apps/global_preferences.h
  apps/settings/base.de.i18n
  apps/settings/base.en.i18n
  apps/settings/base.es.i18n
  apps/settings/base.fr.i18n
  apps/settings/base.pt.i18n
  apps/settings/main_controller_prompt_beta.cpp
  apps/settings/main_controller_prompt_none.cpp
  apps/settings/main_controller_prompt_update.cpp
  apps/settings/sub_menu/exam_mode_controller.cpp
  apps/settings/sub_menu/exam_mode_controller.h
  apps/settings/sub_menu/preferences_controller.cpp
  apps/title_bar_view.cpp
  ion/src/device/n0110/drivers/led.cpp
  ion/src/device/shared/drivers/exam_mode.cpp
  poincare/include/poincare/preferences.h
  poincare/src/preferences.cpp
Labels: Bug, Feature

#108 Added missing names, added usernames, closes #89
  apps/settings/main_controller_prompt_beta.cpp
  apps/settings/main_controller_prompt_none.cpp
  apps/settings/main_controller_prompt_update.cpp
  apps/settings/sub_menu/contributors_controller.cpp
  apps/settings/sub_menu/contributors_controller.h
  apps/shared.universal.i18n
Labels: Feature

#112 [settings/math] Changed from "Multiply symbol" to "Multiply", fixed #109
  apps/settings/base.de.i18n
  apps/settings/base.en.i18n
  apps/settings/base.es.i18n
  apps/settings/base.fr.i18n
  apps/settings/base.pt.i18n
Labels: Change

#114 [build] Added target doc, using doxygen.
  Makefile
  build/doc/Doxyfile
Labels: Feature

#110 [ion/keyboard] Fixed layout. Added shift + (
  ion/include/ion/keyboard/layout_B2/layout_events.h
  ion/include/ion/keyboard/layout_B3/layout_events.h
Labels: Bug, Feature

#113 Added `make PLATFORM=simulator run`
  Makefile
Labels: Feature

#117 [simulator] changed apps id, changed icon, removed telemetry
  ion/src/simulator/android/Makefile
  ion/src/simulator/android/build.gradle
  ion/src/simulator/android/src/AndroidManifest.xml
  ion/src/simulator/android/src/cpp/images.cpp
  ion/src/simulator/android/src/cpp/telemetry.cpp
  ion/src/simulator/android/src/java/io/github/omega/simulator/OmegaActivity.java
  ion/src/simulator/android/src/res/values/colors.xml
  ion/src/simulator/assets/logo.svg
  ion/src/simulator/ios/Info.plist
  ion/src/simulator/macos/Info.plist
  ion/src/simulator/shared/events_keyboard.cpp
  ion/src/simulator/shared/main_sdl.cpp
  ion/src/simulator/shared/platform.h
Labels: Change
