Repository Omega-Numworks/Omega, pull requests merged in 2020-07, with the labels that each got.

#363 Changed simulator background
  ion/src/simulator/assets/background.jpg
Labels: Type: Feature

#366 Adding file support to micropython
  apps/code/catalog.de.i18n
  apps/code/catalog.en.i18n
  apps/code/catalog.es.i18n
  apps/code/catalog.fr.i18n
  apps/code/catalog.hu.i18n
  apps/code/catalog.pt.i18n
  apps/code/catalog.universal.i18n
  apps/code/python_toolbox.cpp
  apps/code/toolbox.de.i18n
  apps/code/toolbox.en.i18n
  apps/code/toolbox.es.i18n
  apps/code/toolbox.fr.i18n
  apps/code/toolbox.hu.i18n
  apps/code/toolbox.pt.i18n
  apps/code/toolbox.universal.i18n
  ion/include/ion/storage.h
  python/Makefile
  python/port/builtins.c
  python/port/genhdr/qstrdefs.in.h
  python/port/mod/ion/file.cpp
  python/port/mod/ion/file.h
  python/port/mod/ion/modion.h
  python/port/mod/ion/modion_table.cpp
Labels: Type: Feature

#369 [apps/home] Made external apps selectable again.
  apps/home/controller.cpp
Labels: Type: Bug

#370 [escher] Fixed alpha+arrow / alpha-lock + arrow
  escher/include/escher/text_input.h
  escher/src/selectable_table_view.cpp
  escher/src/text_area.cpp
  escher/src/text_field.cpp
  escher/src/text_input.cpp
Labels: Type: Bug

#371 [Fix] Missing translations
  apps/code/base.hu.i18n
  apps/code/base.it.i18n
  apps/code/base.nl.i18n
  apps/code/base.pt.i18n
  apps/code/catalog.de.i18n
  apps/code/catalog.hu.i18n
  apps/code/catalog.it.i18n
  apps/code/catalog.nl.i18n
  apps/code/catalog.pt.i18n
  apps/code/toolbox.it.i18n
  apps/code/toolbox.nl.i18n
  apps/external/Makefile
  apps/external/base.it.i18n
  apps/external/base.nl.i18n
  apps/settings/base.it.i18n
  apps/settings/base.nl.i18n
  apps/shared.hu.i18n
  apps/shared.it.i18n
  apps/shared.nl.i18n
  apps/toolbox.it.i18n
  apps/toolbox.nl.i18n
  apps/toolbox.pt.i18n
  build/config.mak
Labels: Type: Translation

#378 [ion/kb] Reverted #370, found a better way to fix.
  escher/include/escher/text_input.h
  escher/src/selectable_table_view.cpp
  escher/src/text_area.cpp
  escher/src/text_field.cpp
  escher/src/text_input.cpp
  ion/src/shared/events_keyboard.cpp
Labels: Type: Change

#380 [Fix] Fixed non-erasable empty character
  poincare/src/layout_cursor.cpp
Labels: Type: Bug

#381 [Fix] Fixed Units to work with the new
  poincare/include/poincare/unit.h
Labels: Type: Bug

#384 [Translation] Translated constants in Italian and NL
  apps/toolbox.en.i18n
  apps/toolbox.it.i18n
  apps/toolbox.nl.i18n
Labels: Type: Translation

#385 [ion] Fixed issue with backspace
  ion/src/shared/events_keyboard.cpp
Labels: Type: Bug

#387 [mpy] Fix crash on append on new file, new os module
  apps/code/script_template.cpp
  ion/include/ion/storage.h
  ion/src/shared/storage.cpp
  python/Makefile
  python/port/genhdr/qstrdefs.in.h
  python/port/mod/ion/file.cpp
  python/port/mod/os/modos.cpp
  python/port/mod/os/modos.h
  python/port/mod/os/modos_table.c
  python/port/mod/os/uname_result.cpp
  python/port/mod/os/uname_result.h
  python/port/mpconfigport.h
Labels: Type: Feature

#389 Omega 1.20.2
  Makefile
  apps/code/app.cpp
  apps/code/app.h
  apps/code/catalog.de.i18n
  apps/code/catalog.en.i18n
  apps/code/catalog.es.i18n
  apps/code/catalog.fr.i18n
  apps/code/catalog.hu.i18n
  apps/code/catalog.it.i18n
  apps/code/catalog.nl.i18n
  apps/code/catalog.pt.i18n
  apps/code/catalog.universal.i18n
  apps/code/python_toolbox.cpp
  apps/code/toolbox.universal.i18n
  ion/src/simulator/android/Makefile
  ion/src/simulator/android/build.gradle
  ion/src/simulator/android/src/java/com/numworks/calculator/EpsilonActivity.java
  ion/src/simulator/android/src/java/io/github/omega/simulator/OmegaActivity.java
  ion/src/simulator/assets/logo.svg
  ion/src/simulator/shared/main_sdl.cpp
  python/port/mod/os/uname_result.cpp
  python/port/mod/os/uname_result.h
Labels: Type: Feature

#390 [apps/settings] remove LEDS_CHOICE
  Makefile
  apps/apps_container.cpp
  apps/exam_mode_configuration.h
  apps/exam_mode_configuration_non_official.cpp
  apps/settings/sub_menu/exam_mode_controller.cpp
  apps/settings/sub_menu/exam_mode_controller.h
  apps/settings/sub_menu/preferences_controller.cpp
  apps/shared.de.i18n
  apps/shared.en.i18n
  apps/shared.es.i18n
  apps/shared.fr.i18n
  apps/shared.hu.i18n
  apps/shared.it.i18n
  apps/shared.nl.i18n
  apps/shared.pt.i18n
  build/config.mak
  build/defaults.mak
  poincare/include/poincare/preferences.h
  poincare/src/preferences.cpp
Labels: Type: Change

#391 [username] Change USERNAME to OMEGA_USERNAME
  README.md
  apps/Makefile
  apps/settings/main_controller.cpp
  apps/settings/main_controller.h
  apps/settings/sub_menu/about_controller.cpp
  apps/settings/sub_menu/about_controller.h
  build/config.mak
  build/defaults.mak
  docker/build
  ion/Makefile
  ion/include/ion.h
  ion/src/shared/platform_info.cpp
Labels: Type: Change

#392 [ion/src/simulator] Visual keyboard only change state on keydown
  ion/src/simulator/shared/keyboard_sdl.cpp
Labels: Type: Feature

#393 [Apps/home] Change menu behaviour with incomplete lines
  apps/home/controller.cpp
  escher/include/escher/selectable_table_view.h
  escher/src/selectable_table_view.cpp
Labels: Type: Feature
