Repository Omega-Numworks/Omega, pull requests merged in 2020-11, with the labels that each got.

#415 [Ion/usb] Changed URL in order to have easier update
  ion/src/device/shared/usb/calculator.h
Labels: Type: Change

#429 [GitHub] Fix n0100 readme
  README.md
Labels: Type: Bug

#430 Translated some missing stuff to spanish
  apps/code/base.es.i18n
  apps/external/base.es.i18n
  apps/home/base.es.i18n
  apps/on_boarding/base.es.i18n
  apps/settings/base.es.i18n
Labels: Type: Translation
