Repository Omega-Numworks/Omega, pull requests merged in 2020-03, with the labels that each got.

#311 Fixed display bug where "x=a(x)" got cutoff
  apps/calculation/calculation.cpp
Labels: Bug

#298 Removed duplicate rule, deleted .gradle, added to gitignore.
  .gitignore
  build/targets.device.n0110.mak
  ion/src/simulator/android/.gradle/5.2.1/fileChanges/last-build.bin
  ion/src/simulator/android/.gradle/5.2.1/fileHashes/fileHashes.lock
  ion/src/simulator/android/.gradle/5.2.1/gc.properties
Labels: Change

#312 Added message when compilation starts.
  Makefile
  build/pimp.mak
Labels: Feature

#244 [Feature] Some "Freedom Units"
  apps/math_toolbox.cpp
  apps/shared.universal.i18n
  apps/toolbox.de.i18n
  apps/toolbox.en.i18n
  apps/toolbox.es.i18n
  apps/toolbox.fr.i18n
  apps/toolbox.hu.i18n
  apps/toolbox.pt.i18n
  poincare/include/poincare/unit.h
Labels: Feature

#318 [Fix] Compact cutoff bug
  apps/calculation/calculation.cpp
Labels: Bug

#320 [Feature] Shift + Home is now a shortcut to go to calculation (or the first app)
  apps/apps_container.cpp
  ion/include/ion/events.h
  ion/include/ion/keyboard/layout_B2/layout_events.h
  ion/include/ion/keyboard/layout_B3/layout_events.h
Labels: Feature
