Repository Omega-Numworks/Omega, pull requests merged in 2020-06, with the labels that each got.

#345 [Feature] RGB files compatibility
  escher/image/inliner.c
Labels: Feature

#349 Fixed external app color bug, made external on home menu default
  apps/home/app_cell.cpp
  apps/home/app_cell.h
  build/config.mak
  escher/src/palette.cpp
Labels: Bug, Feature

#338 [Change] A way to stop the US Unit's imperialism
  poincare/include/poincare/unit.h
  poincare/src/multiplication.cpp
Labels: Change

#332 [Feature] Port Omega to the 3DS
  .gitignore
  build/platform.simulator.3ds.mak
  build/targets.simulator.3ds.mak
  build/toolchain.devkitarm.mak
  ion/src/simulator/3ds/Makefile
  ion/src/simulator/3ds/assets/logo.png
  ion/src/simulator/3ds/callback.cpp
  ion/src/simulator/3ds/display.cpp
  ion/src/simulator/3ds/display.h
  ion/src/simulator/3ds/driver/battery.cpp
  ion/src/simulator/3ds/driver/common.cpp
  ion/src/simulator/3ds/driver/common.h
  ion/src/simulator/3ds/driver/display.cpp
  ion/src/simulator/3ds/driver/language.cpp
  ion/src/simulator/3ds/driver/led.cpp
  ion/src/simulator/3ds/driver/usb.cpp
  ion/src/simulator/3ds/events_keyboard.cpp
  ion/src/simulator/3ds/framebuffer.cpp
  ion/src/simulator/3ds/framebuffer.h
  ion/src/simulator/3ds/keyboard.cpp
  ion/src/simulator/3ds/keyboard.h
  ion/src/simulator/3ds/main.cpp
  ion/src/simulator/3ds/main.h
  ion/src/simulator/3ds/platform.h
  ion/src/simulator/3ds/telemetry_init.cpp
  ion/src/simulator/external/config.3ds.mak
  poincare/include/poincare/integer.h
Labels: Feature

#327 [Feature] Add Toolbox / Table shortcuts
  escher/src/nested_menu_controller.cpp
  escher/src/selectable_table_view.cpp
Labels: Feature

#290 [Feature] Add root and log setting
  apps/settings/base.de.i18n
  apps/settings/base.en.i18n
  apps/settings/base.es.i18n
  apps/settings/base.fr.i18n
  apps/settings/base.hu.i18n
  apps/settings/base.pt.i18n
  apps/settings/main_controller.cpp
  apps/settings/main_controller.h
  apps/settings/sub_menu/math_options_controller.cpp
  apps/settings/sub_menu/math_options_controller.h
  apps/settings/sub_menu/preferences_controller.cpp
  escher/src/layout_field.cpp
  poincare/include/poincare/layout_cursor.h
  poincare/include/poincare/preferences.h
  poincare/src/layout_cursor.cpp
  poincare/src/preferences.cpp
Labels: Feature

#350 [Feature] Add \ and @
  ion/include/ion/keyboard/layout_B2/layout_events.h
  ion/include/ion/keyboard/layout_B3/layout_events.h
Labels: Feature

#353 [Fix] Patched colors
  apps/calculation/additional_outputs/complex_graph_cell.cpp
  apps/calculation/additional_outputs/expression_with_equal_sign_view.h
  apps/calculation/additional_outputs/illustration_cell.cpp
  apps/calculation/additional_outputs/scrollable_three_expressions_cell.h
  apps/calculation/additional_outputs/trigonometry_graph_cell.cpp
  apps/code/console_line_cell.cpp
  apps/code/editor_view.cpp
  apps/code/script_parameter_controller.cpp
  apps/hardware_test/keyboard_view.cpp
  apps/probability/distribution_controller.h
  apps/shared/curve_view.cpp
  apps/shared/scrollable_multiple_expressions_view.cpp
  apps/variable_box_empty_controller.cpp
  escher/include/escher/scrollable_expression_view.h
  escher/src/palette.cpp
Labels: Type: Bug

#358 [Docker] Add docker and docker CI
  .github/workflows/ci-docker.yml
  docker/Dockerfile
  docker/build
  docker/readme.md
Labels: Type: Feature

#359 [apps/home] Changed wrong background color on app_cell
  apps/home/app_cell.cpp
Labels: Type: Bug
