Repository Omega-Numworks/Omega, pull requests merged in 2020-01, with the labels that each got.

#137 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/problems-during-installation.md
  build/config.mak
Labels: Feature

#126 Remove static buffers
  apps/battery_view.cpp
  apps/calculation/test.py
  apps/hardware_test/arrow_view.cpp
  apps/lock_view.cpp
  apps/shared/ok_view.cpp
  apps/shared/round_cursor_view.cpp
  apps/solver/equation_list_view.cpp
  build/device/ram_map.py
  build/targets.device.mak
  escher/src/chevron_view.cpp
  escher/src/ellipsis_view.cpp
  escher/src/gauge_view.cpp
  escher/src/key_view.cpp
  escher/src/switch_view.cpp
  poincare/include/poincare/parenthesis_layout.h
  poincare/src/left_parenthesis_layout.cpp
  poincare/src/parenthesis_layout.cpp
  poincare/src/right_parenthesis_layout.cpp
  poincare/src/trigonometry_cheat_table.cpp
Labels: Change

#159 Fixed apps dependency in ion.
  ion/src/device/n0110/drivers/led.cpp
Labels: Bug

#152 Corrected *10^
  poincare/src/layout_cursor.cpp
Labels: Bug

#161 Translated to Hungarian
  apps/external/base.hu.i18n
Labels: Translation

#167 switching right and up in get_keys()
  python/port/mod/kandinsky/modkandinsky.cpp
Labels: Bug

#191 Shift+Up and Shift+Down in python editor (closes #177)
  escher/src/text_area.cpp
  ion/include/ion/events.h
  ion/include/ion/keyboard/layout_B2/layout_events.h
  ion/include/ion/keyboard/layout_B3/layout_events.h
Labels: Feature

#192 Added option to duplicate scripts (closes #176)
  apps/code/base.de.i18n
  apps/code/base.en.i18n
  apps/code/base.es.i18n
  apps/code/base.fr.i18n
  apps/code/base.hu.i18n
  apps/code/base.pt.i18n
  apps/code/menu_controller.cpp
  apps/code/menu_controller.h
  apps/code/script_parameter_controller.cpp
  apps/code/script_parameter_controller.h
Labels: Feature

#179 Remove External app for unsupported devices (web/n0100) and adds a ba…
  Makefile
  apps/Makefile
  apps/calculation/app.cpp
  apps/calculation/app.h
  apps/code/app.cpp
  apps/code/app.h
  apps/external/app.cpp
  apps/external/app.h
  apps/graph/app.cpp
  apps/graph/app.h
  apps/home/controller.cpp
  apps/probability/app.cpp
  apps/probability/app.h
  apps/regression/app.cpp
  apps/regression/app.h
  apps/sequence/app.cpp
  apps/sequence/app.h
  apps/settings/app.cpp
  apps/settings/app.h
  apps/solver/app.cpp
  apps/solver/app.h
  apps/statistics/app.cpp
  apps/statistics/app.h
  escher/include/escher/app.h
  escher/src/app.cpp
Labels: Feature, Work in progress

#199 [apps/code] Fixed #198
  apps/code/console_controller.h
Labels: Bug

#211 FCC ID always higlight fix
  apps/settings/sub_menu/about_controller.cpp
Labels: Bug
