Repository Omega-Numworks/Omega, pull requests merged in 2020-02, with the labels that each got.

#222 Fixed #205
  ion/include/ion/keyboard/layout_B2/layout_events.h
  ion/include/ion/keyboard/layout_B3/layout_events.h
Labels: Bug

#228 Patch #226
  ion/include/ion/keyboard/layout_B2/layout_events.h
  ion/include/ion/keyboard/layout_B3/layout_events.h
Labels: Bug

#242 Fixed %
  apps/code/editor_controller.cpp
  escher/src/text_field.cpp
Labels: Bug

#247 Fixed some translations
  apps/toolbox.hu.i18n
Labels: Translation

#248 good stuff
  apps/settings/base.hu.i18n
Labels: Translation

#249 Epstein did not kill himself
  apps/probability/base.hu.i18n
Labels: Translation

#250 fixed even more translations
  apps/settings/base.hu.i18n
Labels: Translation

#251 Fixed most of the translations(probably all of them)
  apps/calculation/base.hu.i18n
  apps/code/base.hu.i18n
  apps/code/catalog.hu.i18n
  apps/graph/base.hu.i18n
  apps/regression/base.hu.i18n
  apps/settings/base.hu.i18n
  apps/shared.hu.i18n
  apps/statistics/base.hu.i18n
  apps/toolbox.hu.i18n
Labels: Translation

#262 Free 1776 bytes of heap by making sTableRows const
  poincare/src/trigonometry_cheat_table.cpp
Labels: Change

#268 Moved the result display settings to the math sub-menu
  apps/settings/main_controller.cpp
  apps/settings/main_controller.h
  apps/settings/main_controller_prompt_beta.cpp
  apps/settings/main_controller_prompt_none.cpp
  apps/settings/main_controller_prompt_update.cpp
  apps/settings/sub_menu/math_options_controller.cpp
  apps/settings/sub_menu/math_options_controller.h
Labels: Change

#271 Update strings.xml
  ion/src/simulator/android/src/res/values/strings.xml
Labels: Change

#272 [Fix] Improved the compact result display
  apps/calculation/calculation.cpp
  apps/calculation/history_view_cell.cpp
  apps/calculation/history_view_cell.h
Labels: Bug

#281 [Feature] Add name into contributors page
  apps/settings/main_controller.cpp
  apps/settings/main_controller.h
  apps/settings/sub_menu/contributors_controller.cpp
  apps/shared.universal.i18n
Labels: Feature

#291 [Feature] Update to latest Epsilon v13
  apps/code/console_controller.cpp
  poincare/include/poincare/expression.h
  poincare/include/poincare/tree_handle.h
  poincare/include/poincare/tree_node.h
  poincare/include/poincare/tree_pool.h
  poincare/src/expression.cpp
  poincare/src/solver.cpp
  poincare/src/tree_pool.cpp
  poincare/test/function_solver.cpp
Labels: Feature

#293 Allow simulator to be loaded with multiple scripts.
  apps/code/app.cpp
Labels: Feature

#295 Bring Alpha+Up/Down/Left/Right scrolls to top/bottom/left/right back.
  escher/src/text_area.cpp
  ion/include/ion/events.h
  ion/include/ion/keyboard/layout_B2/layout_events.h
  ion/include/ion/keyboard/layout_B3/layout_events.h
Labels: Change

#287 [Feature] New Constants & Units
  apps/math_toolbox.cpp
  apps/settings/sub_menu/contributors_controller.cpp
  apps/shared.universal.i18n
  apps/toolbox.de.i18n
  apps/toolbox.en.i18n
  apps/toolbox.es.i18n
  apps/toolbox.fr.i18n
  apps/toolbox.hu.i18n
  apps/toolbox.pt.i18n
  kandinsky/fonts/code_points.h
  kandinsky/include/kandinsky/font.h
  poincare/include/poincare/tree_pool.h
  poincare/include/poincare/unit.h
  poincare/src/multiplication.cpp
  poincare/src/unit.cpp
Labels: Feature, Work in progress
