Repository Omega-Numworks/Omega, pull requests merged in 2021-03, with the labels that each got.

#469 [Poincare/parser] support ' as derivative
  poincare/src/parsing/parser.cpp
  poincare/src/parsing/parser.h
  poincare/src/parsing/token.h
  poincare/src/parsing/tokenizer.cpp
Labels: Type: Feature

#500 [apps/code] Fix French translation mistakes
  apps/code/catalog.fr.i18n
Labels: Type: Translation

#504 [themes] Change Atomic app theme
  themes/themes/local/epsilon_dark.json
  themes/themes/local/epsilon_light.json
  themes/themes/local/omega_dark.json
  themes/themes/local/omega_light.json
Labels: Type: Change

#516 [themes] Omega atomic dark
  themes/themes/local/epsilon_dark.json
  themes/themes/local/omega_dark.json
Labels: Type: Change
