Repository Omega-Numworks/Omega, pull requests merged in 2021-02, with the labels that each got.

#461 [Fix] Make CI work again
  .github/workflows/ci-workflow.yml
  .github/workflows/unit-workflow.yml
  apps/Makefile
Labels: Type: Bug

#452 [themes] Wrong colors in Omega Dark
  themes/themes/local/omega_dark/probability/fisher_icon.png
  themes/themes/local/omega_dark/probability/focused_fisher_icon.png
Labels: Type: Bug

#464 [ion] New icon for the macOS simulator
  ion/src/simulator/assets/logoMacOS.png
  ion/src/simulator/shared/apple/helpers.mak
Labels: Type: Feature

#483 [ion] Brand new icon for the Windows simulator
  ion/src/simulator/assets/logoWin.ico
  ion/src/simulator/windows/images.cpp
  ion/src/simulator/windows/resources.rc
Labels: Type: Feature

#484 [ion] Icon for the AUR repo
  ion/src/simulator/assets/logoAUR.png
Labels: Type: Feature

#479 ScriptSize French Translation
  apps/code/base.fr.i18n
Labels: Type: Translation

#474 Fixed python in debug and -j build issues
  apps/Makefile
  python/port/mpconfigport.h
Labels: Type: Bug
